### PR TITLE
Fixes issue #3 by using getTimestamp() instead of getDate()

### PR DESCRIPTION
**Pull request by jalkanen**
This seems to work for me (and tests pass), even though there are no unit tests for multiple level migration.

### CODE REVIEW

**Comment by devshorts** [comment]
Awesome catch and thanks for the pull request! Much appreciated! 

I've checked in a branch for a multi level migration (https://github.com/paradoxical-io/cassandra-loader/tree/bugfix/get-date-tests) that should help you validate this. Can you rebase your code from that branch and if it works we'll merge this into master?

Once we get it validated and merged I'll release a new version. I don't think we've caught this since most people are still on cassandra 2.1 and our usages of the loader (in cassieq) have always been single session generation for test utilities.

**Comment by jalkanen** [comment]
Unfortunately no. The result is:

```
Tests in error: 
  TestDbScripts.test_runner:42 » InvalidQuery Unknown identifier created_date

Tests run: 4, Failures: 0, Errors: 1, Skipped: 0
```

This is however a test failure. The following patch fixes the issue:

```
diff --git a/src/test/java/io/paradoxical/cassandra/loader/TestDbScripts.java b/src/test/java/io/paradoxical/cassandra/loader/TestDbScripts.java
index c22014b..14d69b9 100644
--- a/src/test/java/io/paradoxical/cassandra/loader/TestDbScripts.java
+++ b/src/test/java/io/paradoxical/cassandra/loader/TestDbScripts.java
@@ -28,7 +28,7 @@ public class TestDbScripts {
         DbRunnerConfig dbRunnerConfig = DbRunnerConfig.builder()
                                                       .dbVersion(1)
                                                       .filePath("src/test/resources/init")
-                                                      .recreateDatabase(false)
+                                                      .recreateDatabase(true)
                                                       .build();

         DbScriptsRunner dbScriptsRunner = new DbScriptsRunner(dbRunnerConfig);
```

The reason is that the exec order of tests is not guaranteed and on my machine the upgrade tests run before test_runner().  This means that there's a different DB table with with the same name but different content when test_runner starts, which results in a failure.  Forcing database recreation at test start makes the tests independent of execution order. Alternatively, you could have a different table name for each test.

With this patch my PR passes the tests fine.

**Comment by jalkanen** [comment]
BTW do you want a PR against this branch or do you wish to do the merge yourself to master directly?

**Comment by devshorts** [comment]
@jalkanen lets do it against this branch.  pull in the tests from the other branch and we'll submit it all together.  lets go with the `recreateDatabase(true)` patch since it makes tests simpler (don't have to worry about new keyspaces and creating them and stuff).  Once thats all in we'll merge it up! Thanks!

**Comment by jalkanen** [comment]
OK, I updated the pull request with the test branch and all fixes.  Travis build seems ok (though it seems to be trying to upload the artifacts somewhere and fails, but I think that's beyond this PR.)

**Comment by jakeswenson** [comment]
Agree, ignore the upload issues. Since build is happy i am happy! 
✔️ LGTM

**Comment by devshorts** [comment]
LGTM!

**Comment by devshorts** [comment]
issue #3

**Pull request merged**
