### PR TITLE
Updating pom for shade release

### PR DESCRIPTION
**Pull request by devshorts**
Related to #7

### CODE REVIEW

**Comment by jakeswenson** [comment]
Maybe we should just add this to the release profile instead? Shouldn't need to build the shaded jar every time should we?

**Comment by devshorts** [comment]
does release run for snapshots? If it does then I'll def move it

**Comment by jakeswenson** [comment]
No, but is someone using the shared jar for snapshots?

**Comment by devshorts** [comment]
Guess not, I'm ok to move it into release

**Comment by jakeswenson** [comment]
LGTM ✔️ weird build failure though, not sure what happened.

**Comment by devshorts** [comment]
Yeah, looks like it ran out of memory in the vm. I kicked the build

**Pull request merged**
